version: '3.8'
services:
  dev-database:
    image: 'postgres'
    container_name: 'walking-skeleton-dev-db'
    env_file:
      - .env.development
    ports:
      - 5436:5432
    volumes:
      - ./db_data:/var/lib/postgresql/data/infra
    networks:
      - dev
networks:
  dev:
volumes:
  db_infra:
